[global]
repo1-type=s3
repo1-s3-endpoint=minio:9000
repo1-s3-bucket=opencivic
repo1-s3-key=minioadmin
repo1-s3-key-secret=minioadmin
repo1-s3-uri-style=path
repo1-s3-verify-tls=n
repo1-path=/pgbackrest

[opencivic]
pg1-host=postgres
pg1-port=5432
pg1-user=opencivic
pg1-database=opencivic
