CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE DATABASE keycloak;
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'keycloak') THEN
    CREATE ROLE keycloak WITH LOGIN PASSWORD 'changeme';
  END IF;
END $$;
GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak;
CREATE SCHEMA IF NOT EXISTS platform;
