apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opencivic.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: {{ include "opencivic.name" . }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "opencivic.name" . }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "opencivic.name" . }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NEXT_PUBLIC_API_URL
              value: {{ printf "http://%s-api:%v/api/v1" (include "opencivic.fullname" .) .Values.service.api.port | quote }}
