{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "opencivic.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "opencivic.name" . }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecret }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "opencivic.fullname" . }}-api
                port:
                  number: {{ .Values.service.api.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "opencivic.fullname" . }}-frontend
                port:
                  number: {{ .Values.service.frontend.port }}
{{- end -}}
