{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencivic.fullname" . }}-minio
  labels:
    app.kubernetes.io/name: {{ include "opencivic.name" . }}
    app.kubernetes.io/component: minio
type: Opaque
stringData:
  accessKey: {{ .Values.minio.auth.accessKey | quote }}
  secretKey: {{ .Values.minio.auth.secretKey | quote }}
{{- end }}
