{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencivic.fullname" . }}-postgres
  labels:
    app.kubernetes.io/name: {{ include "opencivic.name" . }}
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  password: {{ .Values.postgres.auth.password | quote }}
{{- end }}
